### ISSUE TITLE
ldd version

### ISSUE THREAD

**Issue by inconnu11** [ubisoft/ubisoft-laforge-daft-exprt#1]
Hi, when I run the ` python training.py  pre_process`, it prompts `Exception: REAPER binary -- Unsupported ldd version: 2.27 < 2.29`. However, my machine could not update the glibc version. Are there any alternatives? Thanks!
![image](https://user-images.githubusercontent.com/38338826/144965909-7f41a5ce-7a9c-4a4b-a7d0-24b4ea877664.png)

**Comment by julianzaidi** [comment]
Hi, this error might be related to your Linux version.
The direct fix for this problem would be for you to build the Docker image, which comes with Ubuntu 20.04 and a glibc version that is superior to 2.29.
If you want to use a local environment, you will need to upgrade the Linux version of your machine.
Let me know if it fixes your problem!

**Comment by inconnu11** [comment]
Hi, I am not sure which part is related with the ldd besides reaper. I replaced the repear with pyworld for the f0 extraction. It seems training successfully now. But I am not sure about whether it will effect other part.

**Comment by julianzaidi** [comment]
glibc version requirements is due to reaper binary. So if you are using pyworld now, you should be good.
