### ISSUE TITLE
How to run the Pre-trained model

### ISSUE THREAD

**Issue by saomya-seasia** [ubisoft/ubisoft-laforge-daft-exprt#11]
Hi @julianzaidi, we tried to run your pre-trained model. However, we are unable to get clarification on the values of the parameters that we need to pass, for instance, specific checkpoints. Also, we received the CUDA out of memory issues too. We would like to run the pre-trained model in Windows instead of Linux. How could we do this?

**Comment by macarbonneau** [comment]
Hello,
         For the checkpoint, you need to point to the file that you downloaded from https://github.com/ubisoft/ubisoft-laforge-daft-exprt/releases

CUDA out of memory means that the memory of your GPU is full. You can try to run it on your CPU or get a GPU with more memory.

To run on Windows, the "simplest" way is to use the docker container provided in this repo. There are special procedure to use CUDA from inside the container. Google should help you.

Good luck

**Comment by anushvst** [comment]
I pointed to that file but got an unpickle error. If you could tell how to run this pretrained model, it would be so kind of you.

**Comment by avst65t** [comment]
> Hello, For the checkpoint, you need to point to the file that you downloaded from https://github.com/ubisoft/ubisoft-laforge-daft-exprt/releases
> 
> CUDA out of memory means that the memory of your GPU is full. You can try to run it on your CPU or get a GPU with more memory.
> 
> To run on Windows, the "simplest" way is to use the docker container provided in this repo. There are special procedure to use CUDA from inside the container. Google should help you.
> 
> Good luck

I pointed to that file but got an unpickle error. If you could tell how to run this pretrained model, it would be so kind of you.
