### ISSUE TITLE
Error while running Pretrained model

### ISSUE THREAD

**Issue by avst65t** [ubisoft/ubisoft-laforge-daft-exprt#12]
Hi @julianzaidi, I pointed to that file in checkpoint argument (archive/data.pkl) but got an unpickle error. If you could tell how to run this pretrained model, it would be so kind of you.

python synthesize.py --output_dir OUTPUT_DIR --checkpoint "archive/data.pkl"

Traceback (most recent call last):
  File "synthesize.py", line 148, in <module>
    file_names, refs, speaker_ids = synthesize(args, use_griffin_lim=True)

  File "synthesize.py", line 38, in synthesize
    checkpoint_dict = torch.load(args.checkpoint, map_location=f'cuda:{0}')

  File "/home/saomya/miniconda3/envs/daft_exprt/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)

  File "/home/saomya/miniconda3/envs/daft_exprt/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)

_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
![Screenshot from 2022-10-26 15-19-43](https://user-images.githubusercontent.com/92500349/197996738-b02183f3-82d7-49a7-8c6d-216c101874e2.png)

**Comment by macarbonneau** [comment]
can you try with the same Pytorch version as the one in the docker file
torch==1.9.0+cu111 torchaudio==0.9.0

**Comment by julianzaidi** [comment]
@anushvst the name of the checkpoint you use for synthesis, `data.pkl`, seems incorrect.
Please refer to the [releases](https://github.com/ubisoft/ubisoft-laforge-daft-exprt/releases/tag/1.0.0) of this repo and take the checkpoint we provide here, i.e. [DaftExprt_LJ_ESD_22kHz](https://github.com/ubisoft/ubisoft-laforge-daft-exprt/releases/download/1.0.0/DaftExprt_LJ_ESD_22kHz).

The command should then be: 
`python synthesize.py --output_dir OUTPUT_DIR --checkpoint PATH/TO/DaftExprt_LJ_ESD_22kHz`

**Comment by anushvst** [comment]
@macarbonneau all dependencies installed correctly

![Screenshot (38)](https://user-images.githubusercontent.com/92500349/198273468-951f2bd0-037d-42d1-b847-794815498c97.png)

@julianzaidi
-Tried the command but still got the error
-Experimented with various permutations but getting errors. Please help, i want this repo working anyhow
-Gave the checkpoint path to both zip and unzipped file ([DaftExprt_LJ_ESD_22kHz)

![Screenshot (37)](https://user-images.githubusercontent.com/92500349/198272684-4de3e0d4-5d11-4bae-b55d-8aa351c92d33.png)

**Comment by avst65t** [comment]
@macarbonneau all dependencies installed correctly

![Screenshot (38)](https://user-images.githubusercontent.com/92500349/198275281-275f92a1-7e07-4816-a7ef-fdb322cae997.png)

@julianzaidi
-Gave the checkpoint path to zipped file i.e DaftExprt_LJ_ESD_22kHz from releases of the repo you provided. It worked but got this error. I got GPU (RTX 1660) on my machine

-Please help Sir, i want this repo working anyhow

![Screenshot (39)](https://user-images.githubusercontent.com/92500349/198275636-c0f94a87-8c5f-4a44-bca2-65747fb61806.png)

**Comment by anushvst** [comment]
QUESTION: will implementation of this pretrained model work only on GPU machine as i tried another approach on cpu only machine

- changed torch.load(... , map_location=torch.device('cpu')) in synthesize.py
- changed def load (... , map_location='cpu', ...) in .../torch/serialization.py

then got this error while running the same command

![Screenshot (8)](https://user-images.githubusercontent.com/92500349/198298362-03b6e956-ddb4-4239-8093-e0efc5804fbd.png)

**Comment by macarbonneau** [comment]
It seems like you have no NVIDIA driver on your system. You should check that you have an NVIDIA GPU installed. 
If you don't, you should change the line 41 in synthetize.py to specify your cpu device.

**Comment by avst65t** [comment]
Okay, thanks @macarbonneau
But any idea about the error i got above while implementing the repo on my GPU?

**Comment by macarbonneau** [comment]
It seems like you machine is attempting to deserialize an object on a CUDA device, but it is unavailable. You should make sure that the device is available. You can check if it is available by typing torch.cuda.is_available(). It should return True

**Comment by julianzaidi** [comment]
The error in the logs above state that you don't have CUDA available on your machine.
Please refer to the [installation](https://github.com/ubisoft/ubisoft-laforge-daft-exprt#installation) section of this repo and verify that you have installed the correct driver, CUDA and CuDNN versions.

**Comment by avst65t** [comment]
@macarbonneau @julianzaidi 
It worked like a charm. Thank you so much for your valuable inputs. You're the best.
All i am left with is how to input my own reference audio & text to the model to get the output. Is there a particular argument i can pass to get the result?

**Comment by julianzaidi** [comment]
Glad it worked for you!
For new text you can modify the file [sentence.txt](https://github.com/ubisoft/ubisoft-laforge-daft-exprt/blob/master/scripts/benchmarks/english/sentences.txt).
For new reference audios, you can add .wav files into the [style_bank](https://github.com/ubisoft/ubisoft-laforge-daft-exprt/tree/master/scripts/style_bank/english) directory.

**Comment by avst65t** [comment]
Yeah it worked perfectly. Thank you so much for your support. I love you guys so much @macarbonneau @julianzaidi
I couldn't had done this without you. Peace be with you.

Last question: how can we train the model with our dataset as there is LJ and ESD in the source code?
I tried to train the model with my dataset but got errors.

**Comment by macarbonneau** [comment]
The training instructions are here: https://github.com/ubisoft/ubisoft-laforge-daft-exprt#quick-start-example
Make sure that your data set complies.

Errors are usually explained in the stack trace. 
Pro tip: Google them.

Good luck

**Comment by julianzaidi** [comment]
Closing since resolved
