### ISSUE TITLE
Problems regarding pretrained model of the daft exprt model

### ISSUE THREAD

**Issue by avst65t** [ubisoft/ubisoft-laforge-daft-exprt#13]
Hi @julianzaidi @macarbonneau, hope you guys are doing well. Just want to ask few queries regarding the model.

- I want to use the model such that it can generate audio in a Hip Hop music artist's voice (he passed away few years ago)
 giving a certain prosody in reference voice and lyrics in the text.

- Curious about the answers to these questions as i am trying to get some audio clips > than 30 seconds

When i run the pretrained model giving reference voice and text, it sounds robotic/unnatural.
- I gave my reference voice (24 sec)
- Text: "Hello John, my name is Don with marketing dot com and I actually just recently came across micro soft and I thought there were some interesting things that we might be able to do together. Um, we do a lot of work in retail and I'm actually coming to New York next week for a conference. So, if you're around I would love to meet with you, buy you a cup of coffee and tell you a little bit more about what we're thinking that we can do for you. Alright, hope to see you soon."

- got this output

https://user-images.githubusercontent.com/92500349/201936746-6b7760a1-fbca-465a-ab27-96ae648564a8.mp4

1. Also in the ouput voice, it generated robotic or un-natural voice till 18 seconds. After that the model generated distorted voice. Any idea about the distortion?

2. Should we give the model short reference voice and text?

3. Can the model produce the output voice greater than 1 minute or it produces short voice?
4. Is punctuation necessary? also will it work if we give "7" instead of "seven" in text file?

5. Want to clarify whose voice the model produces in the output: the reference speaker voice or the model's voice on which it is trained (LJ, ESD)?

6. I am still getting the unnatural (but better than previous) voice after training on the LJ dataset. Any tips how to get the natural voice output?
- Reference voice - LJ's voice
- Text: Hello John, my name is Don with marketing dot com. I actually just recently came across microsoft.
- The output i got was:

https://user-images.githubusercontent.com/92500349/202087380-1858ecab-b32f-4db7-9021-885a185222e0.mp4

- Is it because the model arcitecture used in generating audios in demo page is different than the model architecture present in the repository?
- Any methods to reduce noise in the output voice?

**Comment by julianzaidi** [comment]
Hello,

Regarding the robotic voice, it is because of Griffin-Lim. Please refer to issue #18.
Regarding you question on reference/sentence lengths, we only tested with short to medium references/sentences.
