### ISSUE TITLE
Able to train on LJ & ESD dataset but error in training the model on custom dataset

### ISSUE THREAD

**Issue by avst65t** [ubisoft/ubisoft-laforge-daft-exprt#14]
Hi @julianzaidi @macarbonneau, hope you guys are doing well. Just want to ask few queries regarding the training aspect.

- I tried to train the model on my voice
- Formatted the dataset successfully
- In pre_processing step, got the error:
ValueError: zero-size array to reduction operation minimum which has no identity

- Created directories in this format: work_dir/data_dir/LJ_Speech/wavs
- In wavs folder i gave around 10 audio clips around 2-3 minute length
- Prepared the metadata according to the instructions in the repository

- Should we use short audio clips to train the model?

Any suggestion regarding this will be very kind of you.

**Comment by julianzaidi** [comment]
Hello,

we trained the model using audio clips that have a lenghts similar to that of LJ Speech data set. 
Audios of 2-3 minutes might be too long for training, and you should split those audio clips into shorter utterances.

**Comment by avst65t** [comment]
Okay, thanks.
