### ISSUE TITLE
The pre-trained model does not work.

### ISSUE THREAD

**Issue by chienlinhuang1116** [ubisoft/ubisoft-laforge-daft-exprt#17]
I checked the output of the pre-trained model. The format of the output audio is weird.

/ubisoft-laforge-daft-exprt/scripts/out_dir$ sox --i 1_ref.wav
Input File     : '1_ref.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:03.56 = 56880 samples ~ 266.625 CDDA sectors
File Size      : 114k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM

~/ubisoft-laforge-daft-exprt/scripts/out_dir$ sox --i 2_sentences.txt_line2_spk_10_ref_2_audio_ref.wav
Input File     : '2_sentences.txt_line2_spk_10_ref_2_audio_ref.wav'
Channels       : 1
Sample Rate    : 22050
Precision      : 54-bit
Duration       : 00:00:02.62 = 57856 samples ~ 196.789 CDDA sectors
File Size      : 463k
Bit Rate       : 1.41M
Sample Encoding: 64-bit Floating Point PCM

"2_sentences.txt_line2_spk_10_ref_2_audio_ref.wav" file format error cannot listen.

**Comment by macarbonneau** [comment]
It is difficult to help you....   Do you have a question?
