### ISSUE TITLE
Position-dependent prosody transfer result

### ISSUE THREAD

**Issue by hyzhan** [ubisoft/ubisoft-laforge-daft-exprt#5]
It seem to obtain position-dependent prosody transfer result by utterance-level embedding.
Why location information could be embedded in the representation obtained by mean pool operation?

**Comment by julianzaidi** [comment]
Hi, the explicit conditioning and prediction of low-level prosodic features (i.e. duration, pitch and loudness) encourages the model to capture timing-sensitive prosodic information from the reference utterance. This explains why the model is able to reproduce accurately prosodic patterns like pitch raising at the end of a question.

**Comment by hyzhan** [comment]
Can the model still reproduce prosodic patterns if the FiLM on paper is removed?
Have you done any related experiments?
I wonder how useful FiLM module is?
